spring:
  application:
    name: suppingmall
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  profiles:
    include:
      - oauth
      - email
      - storage
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false

  #DataSource
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: pass


  # Redis & Cache
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

  # NULL Field 제외
  jackson:
    default-property-inclusion: NON_NULL

#Mybatis config
mybatis:
  mapper-locations: classpath:/mappers/*.xml

logging:
  level:
    com.supshop.suppingmall: debug
    org.hibernate.sql: debug
    org.type.descriptor.sql.BasicBinder: trace
#    org.springframework: debug



