spring:
  application:
    name: suppingmall


#DataSource
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suppingmall?autoReconnect=true&useSSL=false
    username: root
    password: pass

#Mybatis config
mybatis:
  mapper-locations: classpath:/mappers/*.xml