spring:
  application:
    name: suppingmall


#DataSource
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: pass

#Mybatis config
mybatis:
  mapper-locations: classpath:/mappers/*.xml


logging:
  level:
    org.hibernate.sql: debug
    org.type.descriptor.sql.BasicBinder: trace
  com.supshop.suppingmall: debug


