spring:
  application:
    name: suppingmall-api
server:
  port: 8080

springdoc:
  api-docs.path: /api/v1/openapi
  swagger-ui.path: /api/v1/swagger

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
