-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 01:36:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema suppingmall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema suppingmall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `suppingmall` DEFAULT CHARACTER SET utf8 ;
USE `suppingmall` ;

-- -----------------------------------------------------
-- Table `suppingmall`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`user` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`user` (
  `user_no` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '유저번호',
  `email` VARCHAR(45) NOT NULL COMMENT '이메일',
  `password` VARCHAR(60) NOT NULL COMMENT '비밀번호',
  `name` VARCHAR(45) NOT NULL COMMENT '이름',
  `nickname` VARCHAR(45) NOT NULL COMMENT '별명',
  `address` VARCHAR(100) NOT NULL COMMENT '주소1',
  `address_detail` VARCHAR(100) NOT NULL COMMENT '주소2',
  `post_no` VARCHAR(45) NOT NULL COMMENT '우편번호',
  `phone_number` VARCHAR(45) NOT NULL COMMENT '핸드폰번호',
  `create_date` DATETIME NOT NULL COMMENT '가입일',
  `update_date` DATETIME NOT NULL COMMENT '수정일',
  `delYn` CHAR(1) NOT NULL COMMENT '삭제여부',
  `role` CHAR(4) NOT NULL COMMENT '권한(코드)',
  `shop_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '판매자명',
  `shop_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '판매자전화번호',
  `shop_address` VARCHAR(100) NULL DEFAULT NULL COMMENT '판매자주소1',
  `shop_address_detail` VARCHAR(100) NULL DEFAULT NULL COMMENT '판매자주소2',
  `shop_post_no` VARCHAR(45) NULL DEFAULT NULL COMMENT '판매자우편번호',
  PRIMARY KEY (`user_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '회원';


-- -----------------------------------------------------
-- Table `suppingmall`.`product_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`product_info` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`product_info` (
  `product_no` BIGINT(20) NOT NULL COMMENT '물품번호',
  `product_name` VARCHAR(45) NOT NULL COMMENT '물품명',
  `price` VARCHAR(45) NOT NULL COMMENT '가격',
  `register_date` DATETIME NOT NULL COMMENT '등록일',
  `seller` BIGINT(20) NOT NULL COMMENT '판매자',
  `brand_name` VARCHAR(45) NOT NULL COMMENT '브랜드',
  `category` CHAR(4) NOT NULL COMMENT '카테고리(코드)',
  `thumbnail` VARCHAR(100) NULL DEFAULT NULL COMMENT '썸네일',
  `picture` VARCHAR(100) NULL DEFAULT NULL COMMENT '물품사진',
  `as_number` VARCHAR(45) NULL DEFAULT NULL COMMENT 'A/S문의',
  PRIMARY KEY (`product_no`),
  INDEX `FK_Product_info_seller_user_user_no_idx` (`seller` ASC) VISIBLE,
  CONSTRAINT `FK_Product_info_seller_user_user_no`
    FOREIGN KEY (`seller`)
    REFERENCES `suppingmall`.`user` (`user_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '판매물품';


-- -----------------------------------------------------
-- Table `suppingmall`.`product_option_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`product_option_info` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`product_option_info` (
  `product_no` BIGINT(20) NOT NULL COMMENT '물품번호',
  `product_option_no` INT(11) NOT NULL COMMENT '물품옵션번호(코드)',
  `name` VARCHAR(45) NOT NULL COMMENT '물품상세이름',
  `price` VARCHAR(45) NOT NULL COMMENT '가격(원가격에 더해짐)',
  `total_count` INT(11) NOT NULL COMMENT '총판매수량',
  `spec_1` VARCHAR(45) NULL,
  `spec_2` VARCHAR(45) NULL,
  `spec_3` VARCHAR(45) NULL,
  `spec_4` VARCHAR(45) NULL,
  `spec_5` VARCHAR(45) NULL,
  `spec_6` VARCHAR(45) NULL,
  `spec_7` VARCHAR(45) NULL,
  `spec_8` VARCHAR(45) NULL,
  `spec_9` VARCHAR(45) NULL,
  `spec_10` VARCHAR(45) NULL,
  PRIMARY KEY (`product_no`, `product_option_no`),
  CONSTRAINT `FK_product_option_info_product_no_product_info_product_no`
    FOREIGN KEY (`product_no`)
    REFERENCES `suppingmall`.`product_info` (`product_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '판매물품옵션';


-- -----------------------------------------------------
-- Table `suppingmall`.`basket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`basket` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`basket` (
  `Basket_no` INT(11) NOT NULL COMMENT '장바구니번호',
  `product_no` BIGINT(20) NOT NULL COMMENT '물품번호',
  `product_option_no` INT(11) NOT NULL COMMENT '물품옵션번호(코드)',
  `user_no` BIGINT(20) NOT NULL COMMENT '유저번호',
  `count` INT(11) NOT NULL COMMENT '판매수량',
  PRIMARY KEY (`Basket_no`),
  INDEX `FK_Basket_product_no_product_option_info_product_no` (`product_no` ASC, `product_option_no` ASC) VISIBLE,
  INDEX `FK_Basket_user_no_user_user_no` (`user_no` ASC) VISIBLE,
  CONSTRAINT `FK_Basket_product_no_product_option_info_product_no`
    FOREIGN KEY (`product_no` , `product_option_no`)
    REFERENCES `suppingmall`.`product_option_info` (`product_no` , `product_option_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Basket_user_no_user_user_no`
    FOREIGN KEY (`user_no`)
    REFERENCES `suppingmall`.`user` (`user_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '장바구니';


-- -----------------------------------------------------
-- Table `suppingmall`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`board` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`board` (
  `board_no` BIGINT(20) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `contents` VARCHAR(1000) NOT NULL,
  `creater` BIGINT(20) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `category` CHAR(4) NULL,
  `product_no` BIGINT(11) NULL,
  PRIMARY KEY (`board_no`),
  INDEX `FK_Board_board_no_user_user_no_idx` (`creater` ASC) VISIBLE,
  INDEX `FK_Board_product_no_product_info_product_no_idx` (`product_no` ASC) VISIBLE,
  CONSTRAINT `FK_Board_board_no_user_user_no`
    FOREIGN KEY (`creater`)
    REFERENCES `suppingmall`.`user` (`user_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Board_product_no_product_info_product_no`
    FOREIGN KEY (`product_no`)
    REFERENCES `suppingmall`.`product_info` (`product_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suppingmall`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`comment` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`comment` (
  `comment_no` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '댓글번호',
  `level` INT(11) NOT NULL COMMENT '수준',
  `title` VARCHAR(45) NOT NULL COMMENT '제목',
  `content` VARCHAR(500) NOT NULL COMMENT '내용',
  `create_date` DATETIME NOT NULL COMMENT '작성일',
  `creater` BIGINT(20) NOT NULL COMMENT '작성자',
  `update_date` DATETIME NOT NULL COMMENT '수정일',
  `secretYn` CHAR(1) NOT NULL COMMENT '비밀여부',
  `score` INT(11) NULL DEFAULT NULL COMMENT '평점',
  `board_no` BIGINT(20) NULL,
  PRIMARY KEY (`comment_no`),
  INDEX `FK_Comment_product_no_user_user_no_idx` (`creater` ASC) VISIBLE,
  INDEX `FK_Comment_board_no_board_board_no_idx` (`board_no` ASC) VISIBLE,
  CONSTRAINT `FK_Comment_product_no_user_user_no`
    FOREIGN KEY (`creater`)
    REFERENCES `suppingmall`.`user` (`user_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Comment_board_no_board_board_no`
    FOREIGN KEY (`board_no`)
    REFERENCES `suppingmall`.`board` (`board_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '댓글';


-- -----------------------------------------------------
-- Table `suppingmall`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`order` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`order` (
  `order_no` BIGINT(20) NOT NULL COMMENT '주문번호',
  `product_no` BIGINT(20) NOT NULL COMMENT '물품번호',
  `product_option_no` INT(11) NOT NULL COMMENT '물품옵션번호(코드)',
  `product_name` VARCHAR(100) NOT NULL COMMENT '물품명',
  `buy_date` DATETIME NOT NULL COMMENT '구매일',
  `buyer` BIGINT(20) NOT NULL COMMENT '구매자',
  `count` INT(11) NOT NULL COMMENT '구매수량',
  `price` VARCHAR(45) NOT NULL COMMENT '주문가격',
  `deliver_no` VARCHAR(45) NULL DEFAULT NULL COMMENT '운송장번호',
  `status` CHAR(4) NOT NULL COMMENT '상태(코드관리)',
  `order_type` CHAR(3) NOT NULL COMMENT '판매/구매(코드)',
  PRIMARY KEY (`order_no`),
  INDEX `FK_Order_buyer_User_user_no_idx` (`buyer` ASC) VISIBLE,
  INDEX `FK_Order_product_detail_no_product_option_info_product_deta_idx` (`product_no` ASC, `product_option_no` ASC) VISIBLE,
  CONSTRAINT `FK_Order_buyer_User_user_no`
    FOREIGN KEY (`buyer`)
    REFERENCES `suppingmall`.`user` (`user_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Order_product_detail_no_product_option_info_product_detail_no`
    FOREIGN KEY (`product_no` , `product_option_no`)
    REFERENCES `suppingmall`.`product_option_info` (`product_no` , `product_option_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '주문';


-- -----------------------------------------------------
-- Table `suppingmall`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`payment` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`payment` (
  `payment_no` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '결제번호',
  `order_no` BIGINT(20) NOT NULL COMMENT '주문번호',
  `paymentedAt` DATETIME NOT NULL COMMENT '결제일',
  `price` VARCHAR(45) NOT NULL COMMENT '결제금액',
  `type` CHAR(4) NOT NULL COMMENT '결제유형(코드관리)',
  `cancleYn` CHAR(1) NOT NULL COMMENT '결제취소여부',
  `type_no` VARCHAR(45) NOT NULL COMMENT '결제매체번호',
  `installment_month` INT(11) NULL DEFAULT NULL COMMENT '할부',
  `cancle_date` DATETIME NULL DEFAULT NULL COMMENT '결제취소일',
  `user_no` BIGINT(20) NOT NULL,
  PRIMARY KEY (`payment_no`),
  INDEX `FK_Payment_user_no_user_user_no_idx` (`user_no` ASC) VISIBLE,
  INDEX `FK_Payment_order_no_Order_order_no_idx` (`order_no` ASC) VISIBLE,
  CONSTRAINT `FK_Payment_order_no_Order_order_no`
    FOREIGN KEY (`order_no`)
    REFERENCES `suppingmall`.`order` (`order_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Payment_user_no_user_user_no`
    FOREIGN KEY (`user_no`)
    REFERENCES `suppingmall`.`user` (`user_no`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '결제이력';


-- -----------------------------------------------------
-- Table `suppingmall`.`code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppingmall`.`code` ;

CREATE TABLE IF NOT EXISTS `suppingmall`.`code` (
  `code_no` CHAR(4) NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_date` DATETIME NULL,
  `updated_date` DATETIME NULL,
  `use_Yn` CHAR(1) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`code_no`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
