-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 18:02:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema suppingmall
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `suppingmall`;

-- -----------------------------------------------------
-- Schema suppingmall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `suppingmall` DEFAULT CHARACTER SET utf8 ;
USE `suppingmall` ;

-- -----------------------------------------------------
-- Table `suppingmall`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`user` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '유저번호',
  `email` VARCHAR(45) NOT NULL COMMENT '이메일',
  `password` VARCHAR(255) NOT NULL COMMENT '비밀번호',
  `name` VARCHAR(45) NOT NULL COMMENT '이름',
  `nickname` VARCHAR(45) NOT NULL COMMENT '별명',
  `city` VARCHAR(100) NOT NULL COMMENT '주소1',
  `city_detail` VARCHAR(100) NOT NULL COMMENT '주소2',
  `zipcode` VARCHAR(45) NOT NULL COMMENT '우편번호',
  `phone_number` VARCHAR(45) NOT NULL COMMENT '핸드폰번호',
  `created_date` TIMESTAMP(3) NULL DEFAULT NULL COMMENT '가입일',
  `updated_date` TIMESTAMP(3) NULL DEFAULT NULL COMMENT '수정일',
  `delete_yes_or_no` CHAR(1) NOT NULL COMMENT '삭제여부',
  `role` CHAR(4) NOT NULL COMMENT '권한(코드)',
  `shop_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '판매자명',
  `shop_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '판매자전화번호',
  `shop_city` VARCHAR(100) NULL DEFAULT NULL COMMENT '판매자주소1',
  `shop_city_detail` VARCHAR(100) NULL DEFAULT NULL COMMENT '판매자주소2',
  `shop_zipcode` VARCHAR(45) NULL DEFAULT NULL COMMENT '판매자우편번호',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '회원';


-- -----------------------------------------------------
-- Table `suppingmall`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`category` (
  `category_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT(20) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_parent_id_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `suppingmall`.`category` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suppingmall`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`product` (
  `product_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '물품번호',
  `name` VARCHAR(45) NOT NULL COMMENT '물품명',
  `price` VARCHAR(45) NOT NULL COMMENT '가격',
  `brand_name` VARCHAR(45) NOT NULL COMMENT '브랜드',
  `registered_date` TIMESTAMP(3) NOT NULL COMMENT '등록일',
  `seller_id` BIGINT(20) NOT NULL COMMENT '판매자',
  `category_id` BIGINT(20) NOT NULL COMMENT '카테고리(코드)',
  `thumbnail` VARCHAR(100) NULL DEFAULT NULL COMMENT '썸네일',
  `picture` VARCHAR(100) NULL DEFAULT NULL COMMENT '물품사진',
  `sale_yes_or_no` VARCHAR(45) NOT NULL COMMENT '판매 여부',
  PRIMARY KEY (`product_id`),
  INDEX `fk_user_id_idx` (`seller_id` ASC) VISIBLE,
  INDEX `fk_product_category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `suppingmall`.`category` (`category_id`),
  CONSTRAINT `fk_product_user_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `suppingmall`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '판매물품';


-- -----------------------------------------------------
-- Table `suppingmall`.`product_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`product_option` (
  `product_id` BIGINT(20) NOT NULL COMMENT '물품번호',
  `product_option_id` INT(11) NOT NULL COMMENT '물품옵션번호',
  `name` VARCHAR(45) NOT NULL COMMENT '물품상세이름',
  `price` VARCHAR(45) NOT NULL COMMENT '가격(원가격에 더해짐)',
  `quantity` INT(11) NOT NULL COMMENT '총판매수량',
  `spec_1` VARCHAR(45) NULL DEFAULT NULL,
  `spec_2` VARCHAR(45) NULL DEFAULT NULL,
  `spec_3` VARCHAR(45) NULL DEFAULT NULL,
  `spec_4` VARCHAR(45) NULL DEFAULT NULL,
  `spec_5` VARCHAR(45) NULL DEFAULT NULL,
  `spec_6` VARCHAR(45) NULL DEFAULT NULL,
  `spec_7` VARCHAR(45) NULL DEFAULT NULL,
  `spec_8` VARCHAR(45) NULL DEFAULT NULL,
  `spec_9` VARCHAR(45) NULL DEFAULT NULL,
  `spec_10` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `product_option_id`),
  CONSTRAINT `fk_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `suppingmall`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '판매물품옵션';


-- -----------------------------------------------------
-- Table `suppingmall`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`basket` (
  `basket_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '장바구니번호',
  `product_id` BIGINT(20) NOT NULL COMMENT '물품번호',
  `product_option_id` INT(11) NOT NULL COMMENT '물품옵션번호(코드)',
  `user_id` BIGINT(20) NOT NULL,
  `count` INT(11) NOT NULL COMMENT '판매수량',
  PRIMARY KEY (`basket_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_product_id_product_option_id_idx` (`product_id` ASC, `product_option_id` ASC) VISIBLE,
  CONSTRAINT `fk_basket_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `suppingmall`.`user` (`user_id`),
  CONSTRAINT `fk_baskset_product_id_product_option_id`
    FOREIGN KEY (`product_id` , `product_option_id`)
    REFERENCES `suppingmall`.`product_option` (`product_id` , `product_option_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '장바구니';


-- -----------------------------------------------------
-- Table `suppingmall`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`board` (
  `board_id` BIGINT(20) AUTO_INCREMENT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `contents` VARCHAR(1000) NOT NULL,
  `category_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  `created_date` TIMESTAMP(3) NOT NULL,
  `updated_date` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`board_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_board_category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `suppingmall`.`category` (`category_id`),
  CONSTRAINT `fk_board_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `suppingmall`.`product` (`product_id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `suppingmall`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suppingmall`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`comment` (
  `comment_id` BIGINT(20)AUTO_INCREMENT NOT NULL AUTO_INCREMENT COMMENT '댓글번호',
  `level` INT(11) NOT NULL COMMENT '수준',
  `title` VARCHAR(45) NOT NULL COMMENT '제목',
  `content` VARCHAR(500) NOT NULL COMMENT '내용',
  `score` INT(11) NULL DEFAULT NULL COMMENT '평점',
  `user_id` BIGINT(20) NOT NULL COMMENT '작성자',
  `board_id` BIGINT(20) NOT NULL COMMENT '게시글',
  `create_date` TIMESTAMP(3) NOT NULL COMMENT '작성일',
  `update_date` TIMESTAMP(3) NOT NULL COMMENT '수정일',
  `secret_yes_or_no` CHAR(1) NOT NULL COMMENT '비밀여부',
  PRIMARY KEY (`comment_id`),
  INDEX `fk_product_id_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_board_id_board_id_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_board_id`
    FOREIGN KEY (`board_id`)
    REFERENCES `suppingmall`.`board` (`board_id`),
  CONSTRAINT `fk_comment_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `suppingmall`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '댓글';


-- -----------------------------------------------------
-- Table `suppingmall`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`delivery` (
  `delivery_id` BIGINT(20)AUTO_INCREMENT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `city_detail` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`delivery_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suppingmall`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`order` (
  `order_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '주문번호',
  `ordered_date` TIMESTAMP(3) NOT NULL COMMENT '구매일',
  `user_id` BIGINT(20) NOT NULL COMMENT '구매자',
  `delivery_id` BIGINT(20) NULL DEFAULT NULL COMMENT '운송정보아이디',
  `status` VARCHAR(30) NOT NULL COMMENT '상태',
  PRIMARY KEY (`order_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_delivery_id_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_delive_id`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `suppingmall`.`delivery` (`delivery_id`),
  CONSTRAINT `fk_order_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `suppingmall`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '주문';


-- -----------------------------------------------------
-- Table `suppingmall`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`order_item` (
  `order_item_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  `product_option_id` INT(11) NOT NULL,
  `count` INT(11) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_id_product_option_id_idx` (`product_id` ASC, `product_option_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `suppingmall`.`order` (`order_id`),
  CONSTRAINT `fk_order_item_product_id_product_option_id`
    FOREIGN KEY (`product_id` , `product_option_id`)
    REFERENCES `suppingmall`.`product_option` (`product_id` , `product_option_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suppingmall`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`payment` (
  `payment_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '결제번호',
  `order_id` BIGINT(20) NOT NULL COMMENT '주문번호',
  `price` VARCHAR(45) NOT NULL COMMENT '결제금액',
  `type` CHAR(4) NOT NULL COMMENT '결제유형(카드,무통장,페이)',
  `type_id` VARCHAR(45) NOT NULL COMMENT '결제매체번호',
  `installment_month` INT(11) NULL DEFAULT NULL COMMENT '할부',
  `cancle_yes_or_no` CHAR(1) NOT NULL COMMENT '결제취소여부',
  `cancle_date` TIMESTAMP NULL DEFAULT NULL COMMENT '결제취소일',
  `paymented_date` TIMESTAMP(3) NOT NULL COMMENT '결제일',
  PRIMARY KEY (`payment_id`),
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `suppingmall`.`order` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '결제이력';


-- -----------------------------------------------------
-- Table `suppingmall`.`product_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppingmall`.`product_detail` (
  `product_id` BIGINT(20) NOT NULL COMMENT '물품번호',
  `product_detail_id` INT(11) NOT NULL COMMENT '물품옵션번호',
  `spec_1` VARCHAR(45) NULL DEFAULT NULL,
  `spec_2` VARCHAR(45) NULL DEFAULT NULL,
  `spec_3` VARCHAR(45) NULL DEFAULT NULL,
  `spec_4` VARCHAR(45) NULL DEFAULT NULL,
  `spec_5` VARCHAR(45) NULL DEFAULT NULL,
  `spec_6` VARCHAR(45) NULL DEFAULT NULL,
  `spec_7` VARCHAR(45) NULL DEFAULT NULL,
  `spec_8` VARCHAR(45) NULL DEFAULT NULL,
  `spec_9` VARCHAR(45) NULL DEFAULT NULL,
  `spec_10` VARCHAR(45) NULL DEFAULT NULL,
  `manuplate_date` DATETIME NULL,
  `assistance_service_number` VARCHAR(45) NULL,
  `contry_of_origin` VARCHAR(45) NULL,
  `manufacturer` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`, `product_detail_id`),
  CONSTRAINT `fk_detail_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `suppingmall`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '판매물품옵션';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
